import DashboardLayout from "./components/layout/DashboardLayout";
import "./globals.css";

export const metadata = {
  title: "Dashboard",
  description: "Generated by Shimanto",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        />
      </head>
      <body className="flex mt-20">
        <DashboardLayout />

        <div className="ml-57 w-full pr-6">{children}</div>
      </body>
    </html>
  );
}
