import Navbar from "./components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Shopery E-Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <head>
          <link
            rel="icon"
            href="/icon?<generated>"
            type="image/<generated>"
            sizes="<generated>"
          />
        </head>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
