import { Toaster } from "react-hot-toast";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";
import { cookies } from "next/headers";

export const metadata = {
  title: "Shopery E-Commerce",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const token = await cookieStore.get("token")?.value;
  return (
    <html lang="en">
      <body>
        <head>
          <link
            rel="icon"
            href="/icon?<generated>"
            type="image/<generated>"
            sizes="<generated>"
          />
        </head>
        <Toaster position="top-center" reverseOrder={false} />
        <Navbar token={token} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
